
GET http://localhost:8080/tournaments HTTP/1.1

###

GET http://localhost:8080/tournaments/1 HTTP/1.1

###

POST http://localhost:8080/tournaments HTTP/1.1
Content-Type: application/json

pagaOpen

###

POST http://localhost:8080/1/team?name=team1&seed=10 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/1/team?name=team2&seed=10 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/1/team?name=team3&seed=10 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/1/team?name=team4&seed=10 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/tournaments/1/firstRound HTTP/1.1
Content-Type: application/json

{
    "matchingAlgorithmName": "Knockout"
}

###

GET http://localhost:8080/tournaments/1/rounds/1 HTTP/1.1

###

GET http://localhost:8080/match/4

###

GET http://localhost:8080/1/team?name=team1

###

PUT http://localhost:8080/1/team/2?newName=teamUNO&newSeed=1

###

PUT http://localhost:8080/match/6?homeTeamPoints=15&awayTeamPoints=10